[package]
name = "anchor-lang"
version = "0.3.0"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/project-serum/anchor"
edition = "2018"
license = "Apache-2.0"
description = "Solana Sealevel eDSL"

[features]
derive = []
fuzzing = ["lazy_static", "spl-token", "bumpalo", "rand", "safe-transmute"]
default = []

[dependencies]
anchor-attribute-access-control = { path = "./attribute/access-control", version = "0.3.0" }
anchor-attribute-account = { path = "./attribute/account", version = "0.3.0" }
anchor-attribute-error = { path = "./attribute/error", version = "0.3.0" }
anchor-attribute-program = { path = "./attribute/program", version = "0.3.0" }
anchor-attribute-state = { path = "./attribute/state", version = "0.3.0" }
anchor-attribute-interface = { path = "./attribute/interface", version = "0.3.0" }
anchor-derive-accounts = { path = "./derive/accounts", version = "0.3.0" }
anchor-attribute-event = { path = "./attribute/event", version = "0.3.0" }
borsh = "0.8.2"
solana-program = "=1.5.15"
thiserror = "1.0.20"
base64 = "0.13.0"

# Fuzz deps.
lazy_static = { version = "1.4.0", optional = true }
spl-token = { version = "3.0.1", features = ["no-entrypoint"], optional = true }
bumpalo = { version = "3.4.0", features = ["collections", "boxed"], optional = true }
rand = { version = "0.7.3", optional = true }
safe-transmute = { version = "0.11.0", optional = true }
